/**
 * ===========================================================================
 * @file    feeder_params.h
 * @brief   C610/M2006拨弹盘速度环PID与安全参数
 * ===========================================================================
 *
 * 实机已经确认方向A为拨弹方向。PID参数仍需根据空载和带弹日志逐步整定。
 */

#ifndef FEEDER_PARAMS_H
#define FEEDER_PARAMS_H

#include "config/control_tuning.h"

/* C610电调ID 3：反馈0x203，控制0x200的DATA[4:5]。 */
#define FEEDER_ESC_ID                         3U
#define FEEDER_CONTROL_STD_ID             0x200U
#define FEEDER_FEEDBACK_STD_ID            0x203U
#define FEEDER_CURRENT_SLOT                   2U

/* STM32F407 CAN1使用过滤器组0~13；组1专用于0x203并路由到FIFO1。 */
#define FEEDER_CAN_FILTER_BANK                1U

/*
 * 拨弹速度环：
 *   - Kp直接按转速误差产生电流；
 *   - Ki按秒积分，并带独立积分限幅和输出饱和anti-windup；
 *   - Kd按误差变化率计算，并使用一阶低通滤波；首次调试保持为0。
 */
#define FEEDER_ENCODER_CPR \
    TUNE_FEEDER_ENCODER_CPR
#define FEEDER_GEAR_RATIO \
    TUNE_FEEDER_GEAR_RATIO
#define FEEDER_PROJECTILES_PER_OUTPUT_REV \
    TUNE_FEEDER_PROJECTILES_PER_OUTPUT_REV
#define FEEDER_CONTINUOUS_SPEED_RPM \
    TUNE_FEEDER_CONTINUOUS_SPEED_RPM
#define FEEDER_REVERSE_SPEED_RPM \
    TUNE_FEEDER_REVERSE_SPEED_RPM
#define FEEDER_TARGET_RAMP_RPM_S \
    TUNE_FEEDER_SPEED_RAMP_RPM_S
#define FEEDER_SINGLE_POSITION_KP_RPM_PER_DEG \
    TUNE_FEEDER_SINGLE_POSITION_KP_RPM_PER_DEG
#define FEEDER_SINGLE_MAX_SPEED_RPM \
    TUNE_FEEDER_SINGLE_MAX_SPEED_RPM
#define FEEDER_SINGLE_OVERSHOOT_PERCENT \
    TUNE_FEEDER_SINGLE_OVERSHOOT_PERCENT
#define FEEDER_SINGLE_POSITION_TOLERANCE_ECD \
    TUNE_FEEDER_SINGLE_POSITION_TOLERANCE_ECD
#define FEEDER_SINGLE_MAX_FORWARD_OVERRUN_ECD \
    TUNE_FEEDER_SINGLE_MAX_FORWARD_OVERRUN_ECD
#define FEEDER_SINGLE_SETTLE_SPEED_RPM \
    TUNE_FEEDER_SINGLE_SETTLE_SPEED_RPM
#define FEEDER_SINGLE_SETTLE_TIME_MS \
    TUNE_FEEDER_SINGLE_SETTLE_TIME_MS
#define FEEDER_SINGLE_HOLD_DEADBAND_ECD \
    TUNE_FEEDER_SINGLE_HOLD_DEADBAND_ECD
#define FEEDER_SINGLE_HOLD_MAX_SPEED_RPM \
    TUNE_FEEDER_SINGLE_HOLD_MAX_SPEED_RPM
#define FEEDER_SINGLE_HOLD_CURRENT_LIMIT_RAW \
    TUNE_FEEDER_SINGLE_HOLD_CURRENT_LIMIT_RAW
#define FEEDER_SPEED_KP \
    TUNE_FEEDER_SPEED_KP
#define FEEDER_SPEED_KI \
    TUNE_FEEDER_SPEED_KI
#define FEEDER_SPEED_KD \
    TUNE_FEEDER_SPEED_KD
#define FEEDER_SPEED_INTEGRAL_LIMIT_RAW \
    TUNE_FEEDER_SPEED_INTEGRAL_LIMIT_RAW
#define FEEDER_SPEED_D_FILTER_HZ \
    TUNE_FEEDER_SPEED_D_FILTER_HZ
#define FEEDER_CONTINUOUS_CURRENT_LIMIT_RAW \
    TUNE_FEEDER_CONTINUOUS_CURRENT_LIMIT_RAW
#define FEEDER_SINGLE_CURRENT_LIMIT_RAW \
    TUNE_FEEDER_SINGLE_CURRENT_LIMIT_RAW
#define FEEDER_REVERSE_CURRENT_LIMIT_RAW \
    TUNE_FEEDER_REVERSE_CURRENT_LIMIT_RAW
#define FEEDER_CURRENT_SLEW_RAW_PER_MS \
    TUNE_FEEDER_CURRENT_SLEW_RAW_PER_MS

/* 反馈、重新解锁和堵转保护。 */
#define FEEDER_FEEDBACK_TIMEOUT_MS \
    TUNE_FEEDER_FEEDBACK_TIMEOUT_MS
#define FEEDER_NEUTRAL_REARM_MS \
    TUNE_FEEDER_NEUTRAL_REARM_MS
#define FEEDER_REARM_MAX_SPEED_RPM \
    TUNE_FEEDER_REARM_MAX_SPEED_RPM
#define FEEDER_STALL_SPEED_THRESHOLD_RPM \
    TUNE_FEEDER_STALL_SPEED_THRESHOLD_RPM
#define FEEDER_STALL_CURRENT_THRESHOLD_RAW \
    TUNE_FEEDER_STALL_CURRENT_THRESHOLD_RAW
#define FEEDER_STALL_TIMEOUT_MS \
    TUNE_FEEDER_STALL_TIMEOUT_MS

/* 停止时仍每10 ms重发一次零电流，运行时控制量变化会立即发送。 */
#define FEEDER_ZERO_KEEPALIVE_MS              10U
#define FEEDER_MAX_CONTROL_DELTA_MS            10U

#if (FEEDER_ESC_ID < 1U) || (FEEDER_ESC_ID > 4U)
#error "FEEDER_ESC_ID must be in the 0x200 control-frame range 1..4"
#endif

#if FEEDER_CURRENT_SLOT != (FEEDER_ESC_ID - 1U)
#error "FEEDER_CURRENT_SLOT must equal FEEDER_ESC_ID - 1"
#endif

#if (FEEDER_CONTINUOUS_CURRENT_LIMIT_RAW > 10000) \
    || (FEEDER_SINGLE_CURRENT_LIMIT_RAW > 10000) \
    || (FEEDER_SINGLE_HOLD_CURRENT_LIMIT_RAW > 10000) \
    || (FEEDER_REVERSE_CURRENT_LIMIT_RAW > 10000)
#error "All C610 current limits must stay within +/-10000"
#endif

#if FEEDER_SINGLE_HOLD_CURRENT_LIMIT_RAW \
    >= FEEDER_SINGLE_CURRENT_LIMIT_RAW
#error "Single-shot hold current must be lower than motion current"
#endif

#endif /* FEEDER_PARAMS_H */
